"""add post name

Revision ID: 22c35ebc23a4
Revises: cc24354f6771
Create Date: 2018-08-11 12:26:23.755879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22c35ebc23a4'
down_revision = 'cc24354f6771'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'name')
    # ### end Alembic commands ###
