"""add comment model

Revision ID: 251dd489dccc
Revises: 9b5d1820b968
Create Date: 2018-08-11 21:32:32.158115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '251dd489dccc'
down_revision = '9b5d1820b968'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('time_add', sa.DateTime(), nullable=True),
    sa.Column('post_doc_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_doc_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comment_time_add'), 'comment', ['time_add'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_comment_time_add'), table_name='comment')
    op.drop_table('comment')
    # ### end Alembic commands ###
