"""add post desc

Revision ID: 4dc3126f82de
Revises: 251dd489dccc
Create Date: 2018-08-13 11:12:02.926171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dc3126f82de'
down_revision = '251dd489dccc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('desc', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'desc')
    # ### end Alembic commands ###
