"""add cate_id

Revision ID: 9b5d1820b968
Revises: 22c35ebc23a4
Create Date: 2018-08-11 20:26:17.460343

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9b5d1820b968'
down_revision = '22c35ebc23a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('cate_id', sa.Integer(), nullable=True))
    op.drop_constraint('post_ibfk_1', 'post', type_='foreignkey')
    op.create_foreign_key(None, 'post', 'category', ['cate_id'], ['id'])
    op.drop_column('post', 'cate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('cate', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.create_foreign_key('post_ibfk_1', 'post', 'category', ['cate'], ['id'])
    op.drop_column('post', 'cate_id')
    # ### end Alembic commands ###
