"""initial migration

Revision ID: a0f911cebcd3
Revises: 
Create Date: 2018-08-10 19:04:10.273301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0f911cebcd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cate', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('post', sa.Column('cate', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'category', ['cate'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'cate')
    op.drop_table('category')
    # ### end Alembic commands ###
